// import './jsxstudy/jsx-study01'
// import './jsxstudy/jsx-study02'
// import './component-basic/first-component'
// import './component-basic/animal-container'
// import './component-basic/props-basic'
// import './component-basic/props-children'
// import './component-intermediate/state-study-3'
// import './component-intermediate/counter-demo'
import './component-intermediate/manipulate-list'